all: install

install:
	@echo -e "\033[0;33mInstalling NodeJS packages for sae-bot\033[0m"
	@echo -e "\033[1;35mMake sure that you are running Node 16.6.0 (or use nvm to change your node version)\033[0m"
	@yarn install

start:
	@yarn start

clean:
	@rm -f yarn-error.log

.PHONY: install start
