name: Lint
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.6.0]
    steps:
    - uses: actions/checkout@v2
    - name: Format
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --cwd sae-bot
    - run: npx eslint 'sae-bot/**/*.js'
    - run: yarn --cwd sae-app
    - run: npx eslint 'sae-app/**/*.{js,jsx}'
