# This is a basic workflow to help you get started with Actions

name: Make format

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Run make format
        uses: ouzi-dev/go-make-action@v1.5.0
        with: 
          target: format

